# WarZone Predictor: Predict Next War Zone {#WarZone-Predictor}

#### Keywords {-}

WarZone, UN, Peace, 

## Who would want to predict the next War Zone

History of human kind is filled with wars that have grown from mere fights between two Homo sapiens groups to full-blown multi nation world wars. Each year billions of dollars are spent on maintaining peace and keeping the borders safe. Global bodies like United Nations were formed to maintain international peace. 

Hence it is necessity to study the historical war zones and try to predict the future so that we can be well prepared and we can diffuse a potential war even before it starts.

This insight would certainly help countries plan their defense budget, strategy and even choice of ally. It will also help organizations like UN to work effectively more than ever before. It can also help MNCs to strategies expansion or oher business decisions.

## How can we predict next War Zone

We source the war and conflict details for past few centuries. We will attribute the war with details such as number of countries that participated, cost of war, human loss, material loss and duration of war.

Then for same time period we will gather various parameters for each of the countries whether that country was at war or at peace-
Economic attributes: GDP, debt, FX, export/import of each country, gun/weapon imports into the country
Government attributes: Local government stability/popularity/majority, democratic or autocratic, government's military spends
Demographic attributes: Population, crime rates, ethnic and religious distribution, transparency index
Geographical attributes: whether it is costal or enclave, number of countries surrounding this country, difficulty of terrain 
Regional unrest history: whether that country/region is known for unrest and wars. 

Now that we have all the required data within acceptable quality range lets look at some interesting findings
1. If we plot scatterplot matrix for following 3 attributes
export/import ratio is less than 5% => imports are 20 times the exports indicating highly dependent country economy
Debt/GDP ration is more than 400% => super leveredged country [@dorfman_forget_nodate]
Government popularity is greater than 80% => Government is capable of taking radical decisions. May be the government became popular due to the promising of radical action.
Then 70% of the time the country went into war in next 3 years.

Now this is very interesting. High import and debt rations indicate that country is going through economic crisis with no recovery in sight. Which might have resulted in anti incumbency and elected a raw aggressive populist government which wants to break the shackles. The road often used to beak free is a war.

2. If we look at histogram of single parameter "number of countries surrounding a country" then the pattern is like a bell curve. Which implies that having very few (0 or 1) or very high (>7) number of neighbors actually lowers the conflict potential of a country. Having no neighbors is quite obvious conflict buster but having more than 7 neighbors might imply that there is more than one bully in vicinity and probably they are busy showing muscles to each other.

3. Another interesting fact is the war rate has sharply decreased from 1950s. Though we expected formation of UN in 1942 would have caused this, but if we drill down then it appears that first use of atom bomb in 1945 has actually reduced the open wars across the region. Same pattern can be seen in Indian sub-continent where post nuclear tests in 1998 there is no war reported. So the data suggests that nuclear weapons have actually reduced the open wars.


## Conclusion

The study gives us useful insight that we can predict whether a country is heading towards a war with some degree of confidence.  
These findings can be used by organizations like UN to run their programs more effectively and possibly prevent a war in making. 
It can also be used by MNCs to direct their business strategies.

A word of caution is this insight can also be misused to push a country into a war by fuelling the reasons of conflicts which otherwise would have been hidden from the external world.

And finally we should also understand that what we are predicting here is open war. The world has already moved ahead in technology and the future war is likely to be a cyber war or a hidden war. These types of wars cannot be predicted by above study.
[@broadberry_economic_nodate]
