# StockTrend:Stock Price Trend Analytics  {#StockTrend}

#### Keywords {-}

stock, money, profit

## StockTrend, Is it for me?

You have shortlisted a stock but you keep wondering when is the right time to buy that stock?  
Are you worried whether stock would go down immediately after you bought it?  
Do you wonder how external events like presidential election or hurricane will affect your stock net worth in the short term?  
And when you finally want to sell it, what is best time to book profit and move out of the market?

If answer to any of these questions is yes then we have a good news for you.
**StockTrend** is innovative analysis tool that helps you answer exactly these kind of questions for any stock listed on NYSE or NSDAQ. No more blind shots into stock market. Use **StockTrend** and make an informed decision about your financial wellbeing.

Stock price cycles through ups and down but many times it shows some interesting pattern with respect to *Time*. *Time* can be looked at from different granularities e.g. hour of the day the trade was booked to see if say afternoon deals are less profitable vs. morning deals? or may be if we look at yearly time and try to figure out if any particular month favors the trade profitability?

**StockTrend** helps you identify all such hidden relations by going through millions of combinations of time slices per stock for decades of price movements and dishes out extremely digestible report of stock price analysis on multiple *Time* metrics to help you make right money making choice.

## StockTrend, Our secret receipe

**StockTrend** scans through thousands of stocks listed and traded on popular US stock exchanges NYSE [@noauthor_nyse_nodate] and NASDAQ [@noauthor_nasdaq_nodate]. We go through years and years of stock prices, trade volumes, lot sizes and lots of other trading information.  

Then we also source market events like   
- Fed rate changes    
- dividends  
- bankruptcy     

We also maintain external events like   
- Presidential election    
- Crude oil price shifts  
- Natural calamities like hurricane or cyclone  
- wars    
- government imposed sanctions on particular country/sector/company.  

Then we munch this humongous data and summarize at different layers using our proprietary algorithms to find patterns and useful stock base prices to helps our customers make informed financial decision.

Our models are based on Box-Jenkins method [@noauthor_boxjenkins_2016] which is pioneer in analyzing time-series data. Using this method as base we have developed world class algorithms that run deep dive analytics to unearth astonishing patterns.

Let me give you some of the simplified analytics that run under the hood. 

Gather stock price for a company over the period of say couple of decades and calculate  

1. Average stock price during each time slice of the day (9:30 am to 4pm split into 30 mins interval slices) vs. Daily average  
This metric when analyzed over period of time can generally show if specific stock shows tendency to open high/low and then stay flat or taper down during the day  
e.g. Usually this kind of behavior is shown by stocks affected by their offshore activities where the breaking news arrives before US wakes up so stock usually fluctuates early in the morning and then stabilizes.

2. Average stock price during each time slice of the Month vs. Monthly average  
There are multiple ways in which we slice a month. One way is to slice a month by week. This metric shows if a particular stock moves during specific week of the month.  
e.g. Usually a stock having lot of derivative position fluctuates more in last week of the month when derivatives settlement happen. So this metric is useful in such highly leveraged stocks.

3. Average stock price during each time slice of the year vs. Yearly average  
Again here there are multiple ways you can slice an year.   
Most popular slice is a quarter, where lots of stocks show tendency to be 'price high' on a particular quarter of every year.  
e.g. Some consumer product and ecommerce stocks show high prices in Jan-March quarter due to high sales volume during year end shopping spree. 

4. Average stock price just before presidential election vs. 1 year after election  
This is usually interesting metric and we can typically see that if one candidate is overwhelming leading the presidential election race then stock market is relatively calm but if there is uncertainty then our metrics can definitely help you calm down by guessing how market might behave during presidential election.

These are some of the very basic and most popular metrics inside **StockTrend**.  
Then there are more complex and proprietary metrics that combine multiple factors by huristically determined weights and connecting the events to predict more accurate stock price moves.  

To give you an example of one of our interesting findings - if ecommerce stock prices do well around Christmas then they also perform better relative to market around coming Valentine's day. We have a theory on why this happens but we will let you guess :)  

## StockTrend, Get it now

We are not yet another trading tips tool. **StockTrend** does not generate trading tips. We don't sell any financial product either and we never will.  

If you are interested in a particular stock and if in need of some deep dive analysis of that stock to understand the intricacies and patterns shown by that particular stock then you are at the right place.  

**StockTrend** calculates hundreds of complex metrics for each of the thousands of stocks for each day, each week, each month, each quarter, each year for decades of stock data from two US stock exchanges, combines it with external events and makes it available to you at on demand so that you can breath easy when you press that buy or sell button.

Don't believe us? Start a free trial and get a glimpse of what **StockTrend** has to offer.