---
title: "W201 Portfolio"
author: "Gaurav Desai"
date: "MIDS Spring 2018"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: yes
biblio-style: apalike
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->
```{r init,include=FALSE,echo=FALSE}
library(magrittr)
readLines('https://www.zotero.org/api/users/4668669/items/top?limit=25&format=bibtex&key=VXdJzTDM2eZyhGSBXUqkAKCc&v=1') %>% writeLines('references.bib')
```


# Welcome! {-}

### Abstract of my first cool idea {-}

Lets predict where the next war will occur!!
My first big idea is to deconstruct the parameters which indicate when an country is moving towards a warzone and try and predict for any given time which areas in the world are prone to war,

### Abstract of my second cool idea {-}

Vero dolor  franzen letterpress.  Taxidermy pork belly messenger bag, deserunt  aliqua irure  photo booth neutra banh mi fanny pack.  Butcher fam heirloom marfa.  Tilde reprehenderit  snackwave tempor.  Qui  pop-up kitsch dolor.  Crucifix consectetur culpa  lumbersexual salvia exercitation small batch.  Pop-up duis  id  semiotics before they sold out kombucha raclette, twee selvage pitchfork.
  
### Abstract of my third cool idea {-}

Activated charcoal succulents ex, pop-up minim neutra pork belly nulla  helvetica semiotics dolor  magna jianbing.  Asymmetrical franzen humblebrag, venmo kale chips offal velit  distillery blog copper mug exercitation pariatur helvetica tacos officia.  Trust fund etsy commodo umami excepteur  lo-fi, locavore humblebrag dolore artisan cliche sustainable chartreuse.  Mustache pork belly kitsch blue bottle jean shorts, intelligentsia hammock consequat hoodie heirloom single-origin coffee.  Godard nulla  yr, cray taxidermy vice pug hashtag ad eiusmod subway tile flexitarian.  Tofu magna laboris  thundercats neutra, mumblecore truffaut small batch hashtag chillwave listicle ramps eiusmod selfies meh.  Bushwick butcher cupidatat  hella organic.

## About the author {-}

Gaurav Desai is software engneer by profession and Data Science enthusiast. Believes that data can tell stories.

*Updated: `r Sys.Date()`*
